apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: local
      defaultBucket: default
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}