apiVersion: 1

datasources:
  - name: DS_INFLUXDB
    type: influxdb
    access: proxy
    url: http://${INFLUXDB_HOST}:8086
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}